Force dnsWeight to be a number
gh-305

I got an error on the last build:

lib: received dnsWeight of 1

/home/runner/work/madliberation/madliberation/node_modules/@aws-cdk/core/lib/runtime.ts:141
    return this.errorMessage + (childMessages.length ? `\n
${childMessages.replace(/\n/g, '\n  ')}` : '');
            ^
Error: Resolution error: Supplied properties not correct for
"CfnRecordSetProps"
  weight: "1" should be a number.

which doesn't make sense to me, because I declare the dnsWeight prop as
a number.